### PR TITLE
Add error classes for PoFile errors

### PR DESCRIPTION
**Pull request by haeky**
RuntimeError doesn't really make sense. I added error classes to be more descriptive.

### CODE REVIEW

**Comment by haeky** [comment]
ping @davidcornu @unixcharles

**Comment by unixcharles** [comment]
:+1:

**Comment by unixcharles** [comment]
PR upstream?

**Comment by davidcornu** [comment]
Can we add tests for these exceptions?

**Comment by haeky** [comment]
I've made the changes @davidcornu

**Comment by haeky** [comment]
I've moved `InvalidMethod` because it was never triggered because of this RegExp (https://github.com/haeky/get_pomo/blob/errors/lib/get_pomo/po_file.rb#L103). I've added the tests to make sure this is properly raised.

**Comment by davidcornu** [comment]
Looks good. Bump your PR to use this branch and submit a PR upstream.

**Pull request merged**
